### ISSUE TITLE
Adding MacOS Postgres.app recommended version 

### ISSUE THREAD

**Issue by kamicut** [ingalls/Hecate#14]
### Context
On macOS, I could only get hecate working with Postgis 2.5+, since it is the first version to have libprotobuf support bundled in [Postgres.app](https://postgresapp.com/downloads.html) [1]. Is this something that should be in the README? 

[1] https://github.com/PostgresApp/PostgresApp/issues/412

cc/ @ingalls

**Comment by ingalls** [comment]
Migrated: https://github.com/Hecate/Hecate/issues/2
